### ISSUE TITLE
AlgorithmManager not found in jwt/web_token.php

### ISSUE THREAD

**Issue by DevoKun** [markgawler/phpbbCognitoAuth#6]
* **phpbb** `3.3.5`
* **php** `7.4.3`

```
[Mon Mar 21 03:07:53.193009 2022] [php7:error] [pid 2556160] [client 10.42.22.235:26902] PHP Fatal error:  

Uncaught Error: Class 'Jose\\Component\\Core\\AlgorithmManager' not found in 
  ext/mrfg/cogauth/jwt/web_token.php:39

Stack trace:

#0 ext/mrfg/cogauth/cognito/web_token_phpbb.php(39): mrfg\\cogauth\\jwt\\web_token->__construct()

#1 cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3054): 
  mrfg\\cogauth\\cognito\\web_token_phpbb->__construct()

#2 cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3004): 
  phpbb_cache_container->getMrfg_Cogauth_WebTokenPhpbbService()

#3 cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3034): 
  phpbb_cache_container->getMrfg_Cogauth_CognitoService()

#4 cache/production/container_4335734bbdd20f586549a504dff5f80c.php(2291): 
  phpbb_cache_container->getMrfg_Cogauth_ListenerService()

#5 vendor/symfony/event-dispa in ext/mrfg/cogauth/jwt/web_token.php on line 39
```

## Steps to reproduce

```bash
mkdir mrfg
cd mrfg
git clone git@github.com:markgawler/phpbbCognitoAuth.git cogauth
cd cogauth
composer install
```

**Comment by DevoKun** [comment]
This issue can be resolved by deleting the stale cache.
```bash
cd cache/production
find -type f -delete
```
